import sys
import json
import webbrowser

import pandas as pd
from PySide6.QtCore import Qt
from PySide6.QtGui import QAction, QFont
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QInputDialog,
    QMainWindow,
    QMenu,
    QVBoxLayout,
)

import spectHR as cs
import spectQt as spQt
from ui_form import Ui_MainWindow


class MainWindow(QMainWindow):
    """
    Main application window for the spectQt ECG pre-processing GUI.

    This window contains:
    - A tree view of available files (e.g., XDF recordings).
    - Multiple Matplotlib-based widgets for viewing preprocessed ECG signals,
      Poincaré plots, and other visualizations.
    - A tab interface to switch between different views.

    Attributes:
    ----------
    ui : Ui_MainWindow
        The autogenerated UI class from Qt Designer.
    workspace : dict
        The structured workspace data loaded from disk or memory.
    prep_plot_widget : PrepPlotWidget
        Widget for displaying the ECG preprocessing plot.
    ibiseries_plot_widget : IBISeriesPlotWidget
        Widget for displaying the IBI series plot.
    poincare_plot_widget : PoincarePlotWidget
        Widget for displaying the Poincaré plot.
    welch_psd_widget : WelchPSDWidget
        Widget for displaying the Welch PSD plot.
    dataset : object
        The currently loaded dataset object with preprocessed ECG data.
    """

    def __init__(self):
        """
        Initialize the MainWindow, set up the UI, load the workspace,
        and connect signals to event handlers.
        """
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.actionAdd_Epoch.triggered.connect(self.add_epoch)
        self.setWindowTitle("spectHR - ECG Preprocessing")
        self.resize(1920, 800)
        self.ui.Splitter.setSizes([200, 1700])

        # Initialize workspace and populate the tree view
        self.workspace = spQt.LoadWorkspace()
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)
        self.ui.actionOpen_Workspace.triggered.connect(self.OpenWorkSpace)
        self.ui.actionOpen_Workspace.setShortcut("Ctrl+O")
        self.ui.actionOpen_Workspace.setStatusTip("Open a workspace file")
        self.ui.actionOpen_Workspace.setToolTip("Open a workspace file")

        # Edit workspace action
        self.ui.actionEdit_Workspace.triggered.connect(self.EditWorkSpace)
        self.ui.actionEdit_Workspace.setShortcut("Ctrl+E")
        self.ui.actionEdit_Workspace.setStatusTip("Edit a workspace file")
        self.ui.actionEdit_Workspace.setToolTip("Edit a workspace file")

        # Save workspace action
        self.ui.actionSave_Workspace.triggered.connect(self.SaveWorkSpace)
        self.ui.actionSave_Workspace.setShortcut("Ctrl+S")
        self.ui.actionSave_Workspace.setStatusTip("Save the current workspace")
        self.ui.actionSave_Workspace.setToolTip("Save the current workspace")

        # Action to open the Documentation site
        self.ui.actionDocumentation.triggered.connect(
            lambda: webbrowser.open("https://github.com/markspan/spectHR/blob/test/readme.MD"))  
        self.ui.actionDocumentation.setShortcut("Ctrl+D")
        self.ui.actionDocumentation.setStatusTip("Open the spectHR documentation")
        self.ui.actionDocumentation.setToolTip("Open the spectHR documentation")


        # Connect the customContextMenuRequested signal to a slot
        self.ui.treeWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.ui.treeWidget.customContextMenuRequested.connect(
            self.show_context_menu)

        # Create and embed the preprocessing plot widget
        self.prep_plot_widget = spQt.PrepPlotWidget()
        layout1 = QVBoxLayout()
        layout1.addWidget(self.prep_plot_widget)
        self.ui.mplPreProcessing.setLayout(layout1)

        # Create and embed the ibiseries plot widget
        self.ibiseries_plot_widget = spQt.IBISeriesPlotWidget()
        layout2 = QVBoxLayout()
        layout2.addWidget(self.ibiseries_plot_widget)
        self.ui.mplIBISeries.setLayout(layout2)

        # Create and embed the Poincare plot widget
        self.poincare_plot_widget = spQt.PoincarePlotWidget()
        layout3 = QVBoxLayout()
        layout3.addWidget(self.poincare_plot_widget)
        self.ui.mplPoincare.setLayout(layout3)

        # Create and embed the Epoch plot widget
        self.epoch_plot_widget = spQt.EpochPlotWidget()
        layout4 = QVBoxLayout()
        layout4.addWidget(self.epoch_plot_widget)
        self.ui.mplEpochs.setLayout(layout4)

        # Create layout for Welch PSD plot widgets (one per epoch)
        self.welch_psd_layout = QVBoxLayout()
        self.ui.scrollAreaWidgetContents.setLayout(self.welch_psd_layout)

        # Create and embed the Parameters plot widget
        self.parameters_plot_widget = spQt.ParametersPlotWidget()
        layout5 = QVBoxLayout()
        layout5.addWidget(self.parameters_plot_widget)
        self.ui.mplParameters.setLayout(layout5)

        # Connect UI signals to their handlers
        self.ui.treeWidget.itemSelectionChanged.connect(self.on_file_selection)
        self.ui.Views.currentChanged.connect(self.on_tab_changed)
        self.dataset = None  # Initialize dataset placeholder

    def OpenWorkSpace(self):
        """
        Open a JSON workspace file, holding the directories.
        """
        file_path, _ = QFileDialog.getOpenFileName(
            self, "Select a file", "", "workspace Files (*.json);;Text Files (*.txt)")
        self.workspace = spQt.LoadWorkspace(file_path)
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)

    def SaveWorkSpace(self):
        """
        Save a JSON workspace file, holding the directories.
        """
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Select a file", "", "workspace Files (*.json);;Text Files (*.txt)")
        if file_path:
            try:
                # Save the workspace to the selected file
                with open(file_path, 'w') as file:
                    json.dump(self.workspace, file, indent=4)
            except Exception as e:
                pass

    def EditWorkSpace(self):
        """
        Edit a JSON workspace file, holding the directories.
        """
        dialog = cs.DirectorySelectorDialog(self.workspace)
        if dialog.exec_() == QInputDialog.Accepted:
            # Update the workspace with the new directories
            self.workspace = dialog.get_directories()
            spQt.PopulateTree(self.ui.treeWidget, self.workspace)

    def show_context_menu(self, position):
        """
        Show a context menu at the specified position.

        Args:
            position (QPoint): The position where the context menu is requested.
        """
        # Get the item that was clicked
        item = self.ui.treeWidget.itemAt(position)
        if not item:
            return

        # Only allow context menu for raw files: the ones with ecg data
        if not item.text(0).lower().endswith('.xdf') \
                and not item.text(0).lower().endswith('.txt') \
                and not item.text(0).lower().endswith('.evt'):
            return

        # Create a context menu
        context_menu = QMenu(self)

        # Create actions for the context menu
        reload_action = QAction("Reload Raw", self)
        clean_action = QAction("ECG Artefact Detection", self)
        invert_action = QAction("Invert ECG Polarity", self)
        retrigger_action = QAction("Retrigger ECG", self)
        classify_action = QAction("(Re-)Classify RTops", self)

        # Connect the actions to their respective functions
        reload_action.triggered.connect(lambda: self.reload(item))
        invert_action.triggered.connect(self.invert)
        clean_action.triggered.connect(self.clean)
        retrigger_action.triggered.connect(self.retrigger)
        classify_action.triggered.connect(self.reClassify)

        # Add the actions to the context menu
        context_menu.addAction(reload_action)
        context_menu.addAction(clean_action)
        context_menu.addAction(invert_action)
        context_menu.addAction(retrigger_action)
        context_menu.addAction(classify_action)
        # Show the context menu at the requested position
        context_menu.exec_(self.ui.treeWidget.viewport().mapToGlobal(position))

    def reClassify(self):
        """
        Reclassify the R-peaks in the ECG signal and update the preprocessing plot.
        """
        if self.dataset is None:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        cs.classify(self.dataset)
        QApplication.restoreOverrideCursor()
        self.show_preprocessing_plot(self.dataset)

    def retrigger(self):
        """
        Retrigger the ECG signal by recalculating the R-peaks and updating the preprocessing plot.
        """
        if self.dataset is None:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        self.dataset = cs.calcPeaks(self.dataset)
        QApplication.restoreOverrideCursor()
        self.show_preprocessing_plot(self.dataset)

    def clean(self):
        """
        Clean up the raw ECG signal.
        """
        QApplication.setOverrideCursor(Qt.WaitCursor)
        self.dataset = cs.ecgArtifactDetection(
            self.dataset, par={'dtw_thresh': 100000})
        QApplication.restoreOverrideCursor()
        self.dataset = cs.calcPeaks(self.dataset)
        self.show_preprocessing_plot(self.dataset)

    def reload(self, item):
        """
        Reload the selected file and update the preprocessing plot.

        Args:
            item: The selected item in the tree view.
        """
        self.dataset = spQt.PreProcessFile(
            self.workspace, item.text(0), reset=True, border=False)
        self.show_preprocessing_plot(self.dataset)

    def invert(self):
        """
        Invert the ECG polarity and update the preprocessing plot.
        """
        if self.dataset is None:
            return

        self.dataset.ecg = cs.TimeSeries(
            self.dataset.ecg.time, -self.dataset.ecg.level)
        self.dataset = cs.calcPeaks(self.dataset)
        self.dataset.save()
        self.show_preprocessing_plot(self.dataset)

    def on_tab_changed(self, index):
        """
        Handler triggered when the user switches tabs in the UI.

        Parameters
        ----------
        index : int
            The index of the newly selected tab.
        """
        QApplication.setOverrideCursor(Qt.WaitCursor)

        if self.dataset is not None:
            self.dataset.save()

        if index == 1 and self.dataset is not None:
            self.show_ibiseries_plot(self.dataset)

        if index == 2 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)

        if index == 3 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)
            self.show_epoch_plot(self.dataset)

        if index == 4 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)
            self.show_welch_psd_plot(self.dataset)

        if index == 5 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)
            self.show_parameters_plot(self.dataset)

        QApplication.restoreOverrideCursor()

    def on_file_selection(self):
        """
        Handler triggered when the user selects a file from the workspace tree.
        It loads and preprocesses the selected file, then updates all
        the plots accordingly.
        """
        selected_items = self.ui.treeWidget.selectedItems()
        if not selected_items:
            return

        file_path = selected_items[0].text(0)
        if file_path in ('XDF Files', 'CARSPAN EVT Files', 'RR Text Files'):
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)

        # Load and preprocess the file
        self.dataset = spQt.PreProcessFile(self.workspace, file_path)

        # Update the UI with the new dataset
        self.show_preprocessing_plot(self.dataset)
        self.show_ibiseries_plot(self.dataset)
        self.show_poincare_plot(self.dataset)
        self.show_epoch_plot(self.dataset)
        self.show_welch_psd_plot(self.dataset)
        self.show_parameters_plot(self.dataset)

        QApplication.restoreOverrideCursor()

    def show_preprocessing_plot(self, data):
        """
        Display the ECG preprocessing results in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing preprocessed ECG signals.
        """
        if data.has_ecg:
            self.ui.Views.setTabVisible(0, True)
            self.ui.Views.setCurrentIndex(0)
            self.prep_plot_widget.prepPlot(data)
        else:
            self.ui.Views.setTabVisible(0, False)
            self.prep_plot_widget.prepPlot(data)
            self.ui.Views.setCurrentIndex(1)

    def show_ibiseries_plot(self, data):
        """
        Display the IBI series plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.ibiseries_plot_widget.plotIBISeries(data)

    def show_epoch_plot(self, data):
        """
        Display the plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.epoch_plot_widget.plotEpoch(data)

    def show_poincare_plot(self, data):
        """
        Display the Poincaré plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if data is not None:
            self.poincare_plot_widget.poincarePlot(data)

    def show_welch_psd_plot(self, dataset):
        """
        Display the Welch PSD plots of the ECG signal in the scroll area.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """

        """
        Plotting is done a bit weird: we need to plot into a void first, to get the maximum 
        and minimum axis values, and then plot again with the same axis limits. This is 
        because the y-axis limits can vary significantly between epochs, and we want to 
        ensure that all plots are comparable.
        """
        if dataset is not None:
            # Clear previous widgets
            while self.welch_psd_layout.count():
                item = self.welch_psd_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
                    widget.deleteLater()

            # Compute PSD per epoch
            # Extract relevant columns for plotting
            active_epochs = {epoch: active for epoch,
                             active in dataset.active_epochs.items() if active}
            visuals = dataset.epochs.loc[dataset.epochs['label'].isin(
                active_epochs.keys())]
            psd_values_list = []
            epoch_names = visuals["label"].tolist()
            # Lists to store y-axis data
            all_y_min = []
            all_y_max = []
            # First pass: plot without setting y-axis limits to gather min/max
            for epoch in epoch_names:
                widget = spQt.WelchPSDPlotWidget()
                spectral_measures = widget.plot_psd(dataset.filtered_by_epoch[epoch], epoch, fs=4, logscale=False, nperseg=256,
                                                    noverlap=128, interp_kind='linear', window='hamming',
                                                    interpolate=True)

                if spectral_measures != -1:
                    psd_values_list.append(spectral_measures)
                    # Get the current y-axis limits
                    y_min, y_max = widget.ax.get_ylim()
                    all_y_min.append(y_min)
                    all_y_max.append(y_max)

            # Determine global y-axis limits
            global_y_min = min(all_y_min)
            global_y_max = max(all_y_max)

            # Second pass: set y-axis limits and add widgets
            for epoch in epoch_names:
                widget = spQt.WelchPSDPlotWidget()
                spectral_measures = widget.plot_psd(dataset.filtered_by_epoch[epoch], epoch, fs=4, logscale=False, nperseg=256,
                                                    noverlap=128, interp_kind='linear', window='hamming',
                                                    interpolate=True)

                if spectral_measures != -1:
                    # Set the global y-axis limits
                    widget.ax.set_ylim(global_y_min, global_y_max)
                    widget.canvas.draw()  # Redraw the canvas with new limits

                    self.welch_psd_layout.addWidget(widget)

            if psd_values_list:
                dataset.psd_values = pd.DataFrame(psd_values_list)

            # Ensure the scroll area is properly set up
            self.ui.scrollArea.setWidgetResizable(True)
            self.ui.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)

    def show_parameters_plot(self, data):
        """
        Display the parameters plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if data is not None:
            self.parameters_plot_widget.display_parameters(data)

    def add_epoch(self):
        """
        Prompt the user for an epoch label and add it to the dataset with the start and end times
        set to the full range of the dataset.
        """
        if self.dataset is None:
            return

        # Prompt the user for an epoch label
        epoch_label, ok = QInputDialog.getText(
            self, 'Add Epoch', 'Epoch Label:')
        if not ok or not epoch_label:
            return

        # Get the full range of the dataset
        start_time = self.dataset.ecg.time.iloc[0]
        end_time = self.dataset.ecg.time.iloc[-1]

        # Add the new epoch to the dataset
        self.dataset.add_epoch_to_dataset(epoch_label, start_time, end_time)

        # Replot the figure to include the new epoch
        self.poincare_plot_widget.poincarePlot(self.dataset)
        self.epoch_plot_widget.plotEpoch(self.dataset)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    # Set global default font
    default_font = QFont("Segoe UI", 12)
    default_font.setBold(False)
    app.setStyle("WindowsVista")
    app.setFont(default_font)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
