import sys

import pandas as pd
from PySide6.QtCore import Qt
from PySide6.QtGui import QAction, QFont
from PySide6.QtWidgets import (
    QApplication,
    QInputDialog,
    QMainWindow,
    QMenu,
    QVBoxLayout,
    QFileDialog,
)

import spectHR as cs
import spectQt as spQt
from ui_form import Ui_MainWindow


class MainWindow(QMainWindow):
    """
    Main application window for the spectQt ECG pre-processing GUI.

    This window contains:
    - A tree view of available files (e.g., XDF recordings).
    - Multiple Matplotlib-based widgets for viewing preprocessed ECG signals,
      Poincaré plots, and other visualizations.
    - A tab interface to switch between different views.

    Attributes:
    ----------
    ui : Ui_MainWindow
        The autogenerated UI class from Qt Designer.
    workspace : dict
        The structured workspace data loaded from disk or memory.
    prep_plot_widget : PrepPlotWidget
        Widget for displaying the ECG preprocessing plot.
    poincare_plot_widget : PoincarePlotWidget
        Widget for displaying the Poincaré plot.
    welch_psd_widget : WelchPSDWidget
        Widget for displaying the Welch PSD plot.
    dataset : object
        The currently loaded dataset object with preprocessed ECG data.
    """

    def __init__(self):
        """
        Initialize the MainWindow, set up the UI, load the workspace,
        and connect signals to event handlers.
        """
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.actionAdd_Epoch.triggered.connect(self.add_epoch)
        self.setWindowTitle("spectHR - ECG Preprocessing")
        self.resize(1920, 800)
        self.ui.Splitter.setSizes([200, 1700])

        # Initialize workspace and populate the tree view
        self.workspace = spQt.LoadWorkspace()
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)
        self.ui.actionOpen_Workspace.triggered.connect(self.OpenWorkSpace)
        # Connect the customContextMenuRequested signal to a slot
        self.ui.treeWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.ui.treeWidget.customContextMenuRequested.connect(self.show_context_menu)

        # Create and embed the preprocessing plot widget
        self.prep_plot_widget = spQt.PrepPlotWidget()
        layout1 = QVBoxLayout()
        layout1.addWidget(self.prep_plot_widget)
        self.ui.mplPreProcessing.setLayout(layout1)

        # Create and embed the ibiseries plot widget
        self.ibiseries_plot_widget = spQt.IBISeriesPlotWidget()
        layout2 = QVBoxLayout()
        layout2.addWidget(self.ibiseries_plot_widget)
        self.ui.mplIBISeries.setLayout(layout2)

        # Create and embed the Poincare plot widget
        self.poincare_plot_widget = spQt.PoincarePlotWidget()
        layout3 = QVBoxLayout()
        layout3.addWidget(self.poincare_plot_widget)
        self.ui.mplPoincare.setLayout(layout3)

        # Create and embed the Epoch plot widget
        self.epoch_plot_widget = spQt.EpochPlotWidget()
        layout4 = QVBoxLayout()
        layout4.addWidget(self.epoch_plot_widget)
        self.ui.mplEpochs.setLayout(layout4)

        # Create layout for Welch PSD plot widgets (one per epoch)
        self.welch_psd_layout = QVBoxLayout()
        self.ui.scrollAreaWidgetContents.setLayout(self.welch_psd_layout)

        # Create and embed the Parameters plot widget
        self.parameters_plot_widget = spQt.ParametersPlotWidget()
        layout5 = QVBoxLayout()
        layout5.addWidget(self.parameters_plot_widget)
        self.ui.mplParameters.setLayout(layout5)

        # Connect UI signals to their handlers
        self.ui.treeWidget.itemSelectionChanged.connect(self.on_file_selection)
        self.ui.Views.currentChanged.connect(self.on_tab_changed)
        self.dataset = None  # Initialize dataset placeholder
    
    def OpenWorkSpace(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select a file", "", "workspace Files (*.json);;Text Files (*.txt)")
        self.workspace = spQt.LoadWorkspace(file_path)
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)

    def show_context_menu(self, position):
        """
        Show a context menu at the specified position.

        Args:
            position (QPoint): The position where the context menu is requested.
        """
        # Get the item that was clicked
        item = self.ui.treeWidget.itemAt(position)
        if not item:
            return

        # Only allow context menu for raw files
        if not item.text(0).lower().endswith('.xdf'):
            return

        # Create a context menu
        context_menu = QMenu(self)

        # Create actions for the context menu
        reload_action = QAction("Reload Raw", self)
        invert_action = QAction("Invert ECG Polarity", self)

        # Connect the actions to their respective functions
        reload_action.triggered.connect(lambda: self.reload(item))
        invert_action.triggered.connect(self.invert)

        # Add the actions to the context menu
        context_menu.addAction(reload_action)
        context_menu.addAction(invert_action)

        # Show the context menu at the requested position
        context_menu.exec_(self.ui.treeWidget.viewport().mapToGlobal(position))

    def reload(self, item):
        """
        Reload the selected file and update the preprocessing plot.

        Args:
            item: The selected item in the tree view.
        """
        self.dataset = spQt.PreProcessFile(item.text(0), reset=True)
        self.show_preprocessing_plot(self.dataset)

    def invert(self):
        """
        Invert the ECG polarity and update the preprocessing plot.
        """
        if self.dataset is None:
            return

        ecg_level = self.dataset.ecg.level
        ecg_time = self.dataset.ecg.time
        self.dataset.ecg = cs.TimeSeries(ecg_time, -ecg_level)
        self.dataset = cs.calcPeaks(self.dataset)
        self.dataset.save()
        self.show_preprocessing_plot(self.dataset)

    def on_tab_changed(self, index):
        """
        Handler triggered when the user switches tabs in the UI.

        Parameters
        ----------
        index : int
            The index of the newly selected tab.
        """
        QApplication.setOverrideCursor(Qt.WaitCursor)

        if self.dataset is not None:
            self.dataset.save()

        if index == 1 and self.dataset is not None:
            self.show_ibiseries_plot(self.dataset)

        if index == 2 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)

        if index == 3 and self.dataset is not None:
            self.show_epoch_plot(self.dataset)

        if index == 4 and self.dataset is not None:
            self.show_welch_psd_plot(self.dataset)

        if index == 5 and self.dataset is not None:
            self.show_parameters_plot(self.dataset)

        QApplication.restoreOverrideCursor()

    def on_file_selection(self):
        """
        Handler triggered when the user selects a file from the workspace tree.
        It loads and preprocesses the selected file, then updates all
        the plots accordingly.
        """
        selected_items = self.ui.treeWidget.selectedItems()
        if not selected_items:
            return

        file_path = selected_items[0].text(0)
        if file_path in ('XDF Files', 'CARSPAN Files'):
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)

        # Load and preprocess the file
        self.dataset = spQt.PreProcessFile(file_path)

        # Update the UI with the new dataset
        #try:
        self.show_preprocessing_plot(self.dataset)
        #self.show_ibiseries_plot(self.dataset)
        self.show_poincare_plot(self.dataset)
        #self.show_epoch_plot(self.dataset)
        #self.show_welch_psd_plot(self.dataset)
        #self.show_parameters_plot(self.dataset)
        #except Exception:
        #    pass
        #finally:
        QApplication.restoreOverrideCursor()

    def show_preprocessing_plot(self, data):
        """
        Display the ECG preprocessing results in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing preprocessed ECG signals.
        """
        if data.has_ecg:
            self.ui.Views.setTabVisible(0, True)
            self.ui.Views.setCurrentIndex(0)
            self.prep_plot_widget.prepPlot(data)
        else:
            self.ui.Views.setTabVisible(0, False)
            self.prep_plot_widget.prepPlot(data)
            self.ui.Views.setCurrentIndex(1)

    def show_ibiseries_plot(self, data):
        """
        Display the IBI series plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.ibiseries_plot_widget.plotIBISeries(data)

    def show_epoch_plot(self, data):
        """
        Display the plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.epoch_plot_widget.plotEpoch(data)

    def show_poincare_plot(self, data):
        """
        Display the Poincaré plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        self.poincare_plot_widget.poincarePlot(data)

    def show_welch_psd_plot(self, dataset):
        """
        Display the Welch PSD plots of the ECG signal in the scroll area.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if dataset is not None:
            # Clear previous widgets
            while self.welch_psd_layout.count():
                item = self.welch_psd_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
                    widget.deleteLater()

            # compute PSD per epoch
            # Extract relevant columns for plotting
            active_epochs = {epoch: active for epoch, active in dataset.active_epochs.items() if active}
            visuals = dataset.epochs.loc[dataset.epochs['label'].isin(active_epochs.keys())]        
            psd_values_list = []
            epoch_names = visuals["label"].tolist()

            for epoch in epoch_names:
                widget = spQt.WelchPSDPlotWidget()
                spectral_measures = widget.plot_psd(dataset.filtered_by_epoch[epoch], epoch, fs=4, logscale=False, nperseg=256,
                                                   noverlap=128, interp_kind='linear', window='hamming',
                                                   interpolate=True)

                if spectral_measures != -1:
                    psd_values_list.append(spectral_measures)
                    self.welch_psd_layout.addWidget(widget)

            if psd_values_list:
                dataset.psd_values = pd.DataFrame(psd_values_list)

            # Ensure the scroll area is properly set up
            self.ui.scrollArea.setWidgetResizable(True)
            self.ui.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)

    def show_parameters_plot(self, data):
        """
        Display the parameters plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        self.parameters_plot_widget.display_parameters(data)

    def add_epoch(self):
        """
        Prompt the user for an epoch label and add it to the dataset with the start and end times
        set to the full range of the dataset.
        """
        if self.dataset is None:
            return

        # Prompt the user for an epoch label
        epoch_label, ok = QInputDialog.getText(self, 'Add Epoch', 'Epoch Label:')
        if not ok or not epoch_label:
            return

        # Get the full range of the dataset
        start_time = self.dataset.ecg.time.iloc[0]
        end_time = self.dataset.ecg.time.iloc[-1]

        # Add the new epoch to the dataset
        self.dataset.add_epoch_to_dataset(epoch_label, start_time, end_time)

        # Replot the figure to include the new epoch
        self.epoch_plot_widget.plotEpoch(self.dataset)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    # Set global default font
    default_font = QFont("Segoe UI", 12)
    default_font.setBold(False)
    app.setStyle("WindowsVista")
    app.setFont(default_font)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
# This code is part of the spectHR project, which is licensed under the GNU License.