import sys

import pandas as pd
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QMainWindow, QVBoxLayout
from PySide6.QtGui import QFont

import spectHR as cs
import spectQt as spQt
import matplotlib.pyplot as plt

from ui_form import Ui_MainWindow
from comel.wrapper import ComelMainWindowWrapper

class MainWindow(ComelMainWindowWrapper):
    """
    Main application window for the spectQt ECG pre-processing GUI.

    This window contains:
    - A tree view of available files (e.g., XDF recordings).
    - Two Matplotlib-based widgets: one for viewing preprocessed ECG signals and
      another for viewing Poincaré plots.
    - A tab interface to switch between different views.

    Attributes:
    ----------
    ui : Ui_MainWindow
        The autogenerated UI class from Qt Designer.
    workspace : dict
        The structured workspace data loaded from disk or memory.
    prep_plot_widget : PrepPlotWidget
        Widget for displaying the ECG preprocessing plot.
    poincare_plot_widget : PoincarePlotWidget
        Widget for displaying the Poincaré plot.
    welch_psd_widget : WelchPSDWidget
        Widget for displaying the Welch PSD plot.
    dataset : object
        The currently loaded dataset object with preprocessed ECG data.
    """

    def __init__(self):
        """
        Initialize the MainWindow, set up the UI, load the workspace,
        and connect signals to event handlers.
        """
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        self.darktheme = False
        self.ui.actionToggle_Theme.triggered.connect(self.do_toggle_theme)
        
        self.setWindowTitle("spectHR - ECG Preprocessing")
        self.resize(1920, 800)
        self.ui.Splitter.setSizes([200, 1700])

        # Initialize workspace and populate the tree view
        self.workspace = spQt.LoadWorkspace()
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)

        # Create and embed the preprocessing plot widget
        self.prep_plot_widget = spQt.PrepPlotWidget()
        layout1 = QVBoxLayout()
        layout1.addWidget(self.prep_plot_widget)
        self.ui.mplPreProcessing.setLayout(layout1)

        # Create and embed the Poincare plot widget
        self.poincare_plot_widget = spQt.PoincarePlotWidget()
        layout2 = QVBoxLayout()
        layout2.addWidget(self.poincare_plot_widget)
        self.ui.mplPoincare.setLayout(layout2)
        
        # Create and embed the Gantt plot widget    
        self.gantt_plot_widget = spQt.GanttPlotWidget()  # Create the GanttPlotWidget instance
        layout3 = QVBoxLayout()  # Create a new layout for the widget
        layout3.addWidget(self.gantt_plot_widget)  # Add the GanttPlotWidget to the layout
        self.ui.mplEpochs.setLayout(layout3)  # Set the layout to the mplEpochs placeholder

        # Create layout for Welch PSD plot widgets (one per epoch)
        self.welch_psd_layout = QVBoxLayout()
        self.ui.scrollAreaWidgetContents.setLayout(self.welch_psd_layout)

        # Create and embed the Parameters plot widget
        self.parameters_plot_widget = spQt.ParametersPlotWidget()
        layout4 = QVBoxLayout()
        layout4.addWidget(self.parameters_plot_widget)
        self.ui.mplParameters.setLayout(layout4)  # Assuming mplParameters is the placeholder for the parameters tab


        # Connect UI signals to their handlers
        self.ui.treeWidget.itemSelectionChanged.connect(self.on_file_selection)
        self.ui.Views.currentChanged.connect(self.on_tab_changed)

        self.dataset = None  # Initialize dataset placeholder

    def do_toggle_theme(self):
        self.darktheme = not self.darktheme
        self.toggle_theme()
        
        if self.darktheme:
            plt.style.use('dark_background')
        else:
            plt.style.use('default')


    def on_tab_changed(self, index):
        """
        Handler triggered when the user switches tabs in the UI.

        Parameters
        ----------
        index : int
            The index of the newly selected tab.

        Side Effects
        ------------
        Saves the current dataset if it exists.
        """
        if self.dataset is not None:
            self.dataset.save()

        if index == 1 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)

        if index == 2 and self.dataset is not None:
            self.show_gantt_plot(self.dataset)

        if index == 3 and self.dataset is not None:
            self.show_welch_psd_plot(self.dataset)

        if index == 4 and self.dataset is not None:  
            self.show_parameters_plot(self.dataset)


    def on_file_selection(self):
        """
        Handler triggered when the user selects a file from the workspace tree.

        It loads and preprocesses the selected file, then updates both
        the preprocessing and Poincaré plots accordingly.
        """
        selected_items = self.ui.treeWidget.selectedItems()
        if not selected_items:
            return

        file_path = selected_items[0].text(0)
        if file_path == 'XDF Files':  # Avoid processing placeholder nodes
            return

        # Load and preprocess the file
        self.dataset = spQt.PreProcessFile(file_path)

        # Update the UI with the new dataset
        self.show_preprocessing_plot(self.dataset)
        self.show_poincare_plot(self.dataset)
        self.show_gantt_plot(self.dataset)
        self.show_welch_psd_plot(self.dataset)
        self.show_parameters_plot(self.dataset)

    def show_preprocessing_plot(self, data):
        """
        Display the ECG preprocessing results in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing preprocessed ECG signals.
        """
        self.prep_plot_widget.prepPlot(data)
        
    def show_gantt_plot(self, data):
        """
        Display the Gantt plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            # Call the method from the GanttPlotWidget to generate and display the plot
            self.gantt_plot_widget.plotGantt(data)
            
    def show_poincare_plot(self, data):
        """
        Display the Poincaré plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        self.poincare_plot_widget.poincarePlot(data)


    # In your MainWindow class, modify the show_welch_psd_plot method as follows:

    def show_welch_psd_plot(self, data):
        """
        Display the Welch PSD plots of the ECG signal in the scroll area.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if data is not None:
            # Clear previous widgets
            while self.welch_psd_layout.count():
                item = self.welch_psd_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
                    widget.deleteLater()  # Ensure the widget is properly deleted

            # Explode and compute PSD per epoch
            exploded = cs.explode(data)

            # Create and display a WelchPSDPlotWidget per epoch
            psd_Values_list = []  # Initialize the list to store PSD values
            for epoch in exploded['epoch'].unique():
                widget = spQt.WelchPSDPlotWidget()
                spectral_measures = widget.plot_psd(exploded, epoch, fs=4, logscale=False, nperseg=256, noverlap=128,
                                interp_kind='linear', window='hamming', interpolate=True)
                
                if spectral_measures != -1:
                    psd_Values_list.append(spectral_measures)
                    self.welch_psd_layout.addWidget(widget)
            data.psd_Values = pd.DataFrame(psd_Values_list)
            # Ensure the scroll area is properly set up
            self.ui.scrollArea.setWidgetResizable(True)
            self.ui.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
            
    def show_parameters_plot(self, data):
        """
        Display the parameters plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        self.parameters_plot_widget.display_parameters(data)
                
if __name__ == "__main__":
    app = QApplication(sys.argv)
    # Set global default font
    default_font = QFont("Segoe UI", 12)
    default_font.setBold(False)
    app.setStyle("WindowsVista")
    app.setFont(default_font)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())