[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
 
[project]
name = "specthr"
version = "1.2.1"
description = "HRV / physiological data tooling"
readme = "README.md"
requires-python = ">=3.11,<3.14"
license = { text = "GPL-2.0-only" }
authors = [
  { name = "M.M. Span", email = "m.m.span@rug.nl" }
]
dependencies = [
    "platformdirs",
    "matplotlib",
    "PySide6",
    "qtawesome",
    "numpy",
    "scipy",
    "pyxdf",
    "mplcursors",
    "h5py",
]
 
[project.optional-dependencies]
dev = [
    "pytest",
]
 
[tool.setuptools.packages]
find = { where = ["src"] , include = ["spectUI*", "spectHR*"]}
 
[project.urls]
Homepage = "https://github.com/MarkSpan/spectHR"
Repository = "https://github.com/MarkSpan/spectHR"
Issues = "https://github.com/MarkSpan/spectHR/issues"