# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Treeframe = QtWidgets.QFrame(parent=self.splitter)
        self.Treeframe.setMaximumSize(QtCore.QSize(512, 16777215))
        self.Treeframe.setStyleSheet("background-color: #f3f3f3;")
        self.Treeframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Treeframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Treeframe.setObjectName("Treeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Treeframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.Treeframe)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.Views = QtWidgets.QTabWidget(parent=self.splitter)
        self.Views.setStyleSheet("background-color: #f3f3f3;")
        self.Views.setDocumentMode(True)
        self.Views.setObjectName("Views")
        self.PreProcessing = QtWidgets.QWidget()
        self.PreProcessing.setObjectName("PreProcessing")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.PreProcessing)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mplPreProcessing = QtWidgets.QWidget(parent=self.PreProcessing)
        self.mplPreProcessing.setObjectName("mplPreProcessing")
        self.horizontalLayout_2.addWidget(self.mplPreProcessing)
        self.Views.addTab(self.PreProcessing, "")
        self.Poincare = QtWidgets.QWidget()
        self.Poincare.setObjectName("Poincare")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Poincare)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mplPoincare = QtWidgets.QWidget(parent=self.Poincare)
        self.mplPoincare.setObjectName("mplPoincare")
        self.horizontalLayout_3.addWidget(self.mplPoincare)
        self.Views.addTab(self.Poincare, "")
        self.Epochs = QtWidgets.QWidget()
        self.Epochs.setObjectName("Epochs")
        self.Views.addTab(self.Epochs, "")
        self.Profiles = QtWidgets.QWidget()
        self.Profiles.setObjectName("Profiles")
        self.Views.addTab(self.Profiles, "")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Workspace = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Workspace.setObjectName("actionOpen_Workspace")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menufile.addAction(self.actionOpen_Workspace)
        self.menuView.addAction(self.actionSettings)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.Views.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Views.setTabText(self.Views.indexOf(
            self.PreProcessing), _translate("MainWindow", "PreProcessing"))
        self.Views.setTabText(self.Views.indexOf(
            self.Poincare), _translate("MainWindow", "Poincare"))
        self.Views.setTabText(self.Views.indexOf(
            self.Epochs), _translate("MainWindow", "Epochs"))
        self.Views.setTabText(self.Views.indexOf(
            self.Profiles), _translate("MainWindow", "Profiles"))
        self.menufile.setTitle(_translate("MainWindow", "WorkSpace"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_Workspace.setText(
            _translate("MainWindow", "Open Workspace"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
