# Copyright (C) 2025 Mark Span <m.m.span@rug.nl>
# SPDX-License-Identifier: GPL-3.0-or-later
# spectUI/_metric_sources.py
"""
AUTO-GENERATED by ``python -m spectUI.metric_docgen``; do not edit.

Static metric -> algorithm map used by :mod:`spectUI.metric_links` when
live introspection is unavailable (the Nuitka onefile build has no git
checkout and cannot read the source of compiled modules).  File paths
only, no line numbers, so the map stays stable as code moves.
"""
from __future__ import annotations

METRIC_ALGORITHM = {
    'ac': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_prsa',
        "chain": ['ac', '_prsa'],
    },
    'band_peak': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'band_peak',
        "chain": ['band_peak'],
    },
    'band_powers': {
        "file": 'src/spectHR/analysis/psd/_band_power.py',
        "algo": 'band_power_rectangular',
        "chain": ['band_powers', 'band_power_rectangular'],
    },
    'band_rel': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'band_rel',
        "chain": ['band_rel'],
    },
    'bp_dbp': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['bp_dbp', '_bp_metric', 'bp_beat_parameters'],
    },
    'bp_map': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['bp_map', '_bp_metric', 'bp_beat_parameters'],
    },
    'bp_pp': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['bp_pp', '_bp_metric', 'bp_beat_parameters'],
    },
    'bp_sbp': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['bp_sbp', '_bp_metric', 'bp_beat_parameters'],
    },
    'count': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'count',
        "chain": ['count'],
    },
    'csi': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'csi',
        "chain": ['csi'],
    },
    'cvi': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'cvi',
        "chain": ['cvi'],
    },
    'cvnn': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'cvnn',
        "chain": ['cvnn'],
    },
    'cvsd': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'cvsd',
        "chain": ['cvsd'],
    },
    'dbp_sd': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['dbp_sd', '_bp_std', 'bp_beat_parameters'],
    },
    'dc': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_prsa',
        "chain": ['dc', '_prsa'],
    },
    'dfa_a1': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'dfa_alpha1',
        "chain": ['dfa_a1', 'dfa_alpha1'],
    },
    'dfa_a2': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'dfa_alpha1',
        "chain": ['dfa_a2', 'dfa_alpha1'],
    },
    'ellipse_area': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'ellipse_area',
        "chain": ['ellipse_area'],
    },
    'heather_index': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'heather_index',
        "chain": ['heather_index'],
    },
    'hf_nu': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'hf_nu',
        "chain": ['hf_nu'],
    },
    'hf_resp_in_band': {
        "file": 'src/spectHR/Tools/RespirationSegmentation.py',
        "algo": 'mean_breath_frequency_hz',
        "chain": ['hf_resp_in_band', '_mean_breath_hz', 'mean_breath_frequency_hz'],
    },
    'hrv_ti': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'hrv_ti',
        "chain": ['hrv_ti'],
    },
    'lf_hf_ratio': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'lf_hf_ratio',
        "chain": ['lf_hf_ratio'],
    },
    'lf_nu': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'lf_nu',
        "chain": ['lf_nu'],
    },
    'ln_hf': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_band_power',
        "chain": ['ln_hf', '_band_power'],
    },
    'max': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'max',
        "chain": ['max'],
    },
    'mean': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'mean',
        "chain": ['mean'],
    },
    'mean_hr': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'mean_hr',
        "chain": ['mean_hr'],
    },
    'median': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'median',
        "chain": ['median'],
    },
    'min': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'min',
        "chain": ['min'],
    },
    'modified_csi': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'modified_csi',
        "chain": ['modified_csi'],
    },
    'nn20': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_nn_pnn',
        "chain": ['nn20', '_nn_pnn'],
    },
    'nn50': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_nn_pnn',
        "chain": ['nn50', '_nn_pnn'],
    },
    'pep': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'pep_ensemble',
        "chain": ['pep', 'pep_ensemble'],
    },
    'pep_b_ms': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'pep_ensemble',
        "chain": ['pep_b_ms', '_pep_detail_field', 'pep_ensemble'],
    },
    'pep_c_ms': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'pep_ensemble',
        "chain": ['pep_c_ms', '_pep_detail_field', 'pep_ensemble'],
    },
    'pep_n_beats': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'pep_ensemble',
        "chain": ['pep_n_beats', '_pep_detail_field', 'pep_ensemble'],
    },
    'pep_q_ms': {
        "file": 'src/spectHR/analysis/icg_metrics.py',
        "algo": 'pep_ensemble',
        "chain": ['pep_q_ms', '_pep_detail_field', 'pep_ensemble'],
    },
    'pnn20': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_nn_pnn',
        "chain": ['pnn20', '_nn_pnn'],
    },
    'pnn50': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_nn_pnn',
        "chain": ['pnn50', '_nn_pnn'],
    },
    'resp_freq': {
        "file": 'src/spectHR/Tools/RespirationSegmentation.py',
        "algo": 'mean_breath_frequency_hz',
        "chain": ['resp_freq', '_mean_breath_hz', 'mean_breath_frequency_hz'],
    },
    'resp_mvo': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": 'resp_beat_parameters',
        "chain": ['resp_mvo', '_resp_metric', 'resp_beat_parameters'],
    },
    'resp_rate_bpm': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": 'resp_rate_bpm',
        "chain": ['resp_rate_bpm'],
    },
    'resp_svo': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": 'resp_beat_parameters',
        "chain": ['resp_svo', '_resp_metric', 'resp_beat_parameters'],
    },
    'rmssd': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'rmssd',
        "chain": ['rmssd'],
    },
    'rrv': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": 'rrv',
        "chain": ['rrv'],
    },
    'rsa': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": '_rsa_metric',
        "chain": ['rsa', '_rsa_metric'],
    },
    'rsa0': {
        "file": 'src/spectHR/analysis/respiration_metrics.py',
        "algo": '_rsa_metric',
        "chain": ['rsa0', '_rsa_metric'],
    },
    'sbp_sd': {
        "file": 'src/spectHR/analysis/bp_metrics.py',
        "algo": 'bp_beat_parameters',
        "chain": ['sbp_sd', '_bp_std', 'bp_beat_parameters'],
    },
    'sd1': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sd1',
        "chain": ['sd1'],
    },
    'sd2': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sd2',
        "chain": ['sd2'],
    },
    'sd_hr': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sd_hr',
        "chain": ['sd_hr'],
    },
    'sd_ratio': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sd_ratio',
        "chain": ['sd_ratio'],
    },
    'sdnn': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sdnn',
        "chain": ['sdnn'],
    },
    'sdsd': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'sdsd',
        "chain": ['sdsd'],
    },
    'stationarity': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'stationarity',
        "chain": ['stationarity'],
    },
    'stationarity_z': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'stationarity_z',
        "chain": ['stationarity_z'],
    },
    'tinn': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'tinn',
        "chain": ['tinn'],
    },
    'total_power': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": '_band_power',
        "chain": ['total_power', '_total_power', '_band_power'],
    },
    'transfer_band_metrics': {
        "file": 'src/spectHR/analysis/transfer.py',
        "algo": 'compute_transfer',
        "chain": ['transfer_band_metrics', 'compute_transfer'],
    },
    'twave_amplitude': {
        "file": 'src/spectHR/analysis/ecg_metrics.py',
        "algo": 'twave_amplitude',
        "chain": ['twave_amplitude'],
    },
}
