import json
import pickle
import sys
import webbrowser

from PySide6.QtCore import QFile, Qt
from PySide6.QtGui import QAction, QFont
from PySide6.QtUiTools import QUiLoader
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QInputDialog,
    QMainWindow,
    QMenu,
    QVBoxLayout,
    QMessageBox,
    QTreeWidgetItem,
)

from pathlib import Path

import spectHR as cs
from spectHR.Actions.calcPeaks import calcPeaks
from spectHR.Actions.ibiClassify import ibiClassify
from spectHR.DataSet.Epoch import Epoch

import spectUI as spQt
from spectHR.Tools.Logger import logger


class MainWindow(QMainWindow):
    """
    Main application window for the spectQt ECG pre-processing GUI.

    This window contains:
    - A tree view of available files (e.g., XDF recordings).
    - Multiple Matplotlib-based widgets for viewing preprocessed ECG signals,
      Poincaré plots, and other visualizations.
    - A tab interface to switch between different views.

    Attributes:
    ----------
    ui : Ui_MainWindow
        The autogenerated UI class from Qt Designer.
    workspace : dict
        The structured workspace data loaded from disk or memory.
    prep_plot_widget : PrepPlotWidget
        Widget for displaying the ECG preprocessing plot.
    HR_plot_widget : IBISeriesPlotWidget
        Widget for displaying the heartrate series.
    poincare_plot_widget : PoincarePlotWidget
        Widget for displaying the Poincaré plot.
    welch_psd_widget : WelchPSDWidget
        Widget for displaying the Welch PSD plot.
    dataset : object
        The currently loaded dataset object with preprocessed ECG data.
    """

    def __init__(self):
        """
        Initialize the MainWindow, set up the UI, load the workspace,
        and connect signals to event handlers.
        """
        super(MainWindow, self).__init__()

        # Load the UI file

        base_dir = Path(__file__).parent
        ui_path = base_dir / "resources" / "form.ui"

        ui_file = QFile(ui_path)
        if not ui_file.open(QFile.ReadOnly):
            logger.error("Cannot open UI file:", ui_file.errorString())
            sys.exit(-1)

        loader = QUiLoader()
        self.ui = loader.load(ui_file)
        ui_file.close()

        self.setCentralWidget(self.ui)

        self.ui.actionAdd_Epoch.triggered.connect(self.add_epoch)
        self.setWindowTitle("spectHR - ECG Preprocessing")
        self.resize(1920, 1280)
        self.ui.Splitter.setSizes([200, 1700])

        # Initialize workspace and populate the tree view
        self.workspace = spQt.LoadWorkspace()

        spQt.PopulateTree(self.ui.treeWidget, self.workspace)
        # CREATE MENU HERE

        # Open workspace action
        self.ui.actionOpen_Workspace.triggered.connect(self.OpenWorkSpace)
        self.ui.actionOpen_Workspace.setShortcut("Ctrl+O")
        self.ui.actionOpen_Workspace.setStatusTip("Open a workspace file")
        self.ui.actionOpen_Workspace.setToolTip("Open a workspace file")

        # Edit workspace action
        self.ui.actionEdit_Workspace.triggered.connect(self.EditWorkSpace)
        self.ui.actionEdit_Workspace.setShortcut("Ctrl+E")
        self.ui.actionEdit_Workspace.setStatusTip("Edit a workspace file")
        self.ui.actionEdit_Workspace.setToolTip("Edit a workspace file")

        # Save workspace action
        self.ui.actionSave_Workspace.triggered.connect(self.SaveWorkSpace)
        self.ui.actionSave_Workspace.setShortcut("Ctrl+S")
        self.ui.actionSave_Workspace.setStatusTip("Save the current workspace")
        self.ui.actionSave_Workspace.setToolTip("Save the current workspace")

        # Action to open the Documentation site
        self.ui.actionDocumentation.triggered.connect(
            lambda: webbrowser.open(
                "https://github.com/markspan/spectHR/blob/test/readme.MD"
            )
        )
        self.ui.actionDocumentation.setShortcut("Ctrl+D")
        self.ui.actionDocumentation.setStatusTip("Open the spectHR documentation")
        self.ui.actionDocumentation.setToolTip("Open the spectHR documentation")

        # Connect the customContextMenuRequested signal to a slot
        self.ui.treeWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.ui.treeWidget.customContextMenuRequested.connect(self.show_context_menu)

        # # Create and embed the preprocessing plot widget
        self.prep_plot_widget = spQt.PrepPlotWidget()
        layout1 = QVBoxLayout()
        layout1.addWidget(self.prep_plot_widget)
        self.ui.mplPreProcessing.setLayout(layout1)

        # # Create and embed the HRseries plot widget
        self.hr_plot_widget = spQt.HRPlotWidget()
        layout2 = QVBoxLayout()
        layout2.addWidget(self.hr_plot_widget)
        self.ui.mplHRSeries.setLayout(layout2)

        # Create and embed the Poincare plot widget
        self.poincare_plot_widget = spQt.PoincarePlotWidget()
        layout3 = QVBoxLayout()
        layout3.addWidget(self.poincare_plot_widget)
        self.ui.mplPoincare.setLayout(layout3)

        # Create and embed the Epoch plot widget
        self.epoch_plot_widget = spQt.EpochPlotWidget()
        layout4 = QVBoxLayout()
        layout4.addWidget(self.epoch_plot_widget)
        self.ui.mplEpochs.setLayout(layout4)

        # Create layout for Welch PSD plot widgets (one per epoch)
        self.welch_psd_layout = QVBoxLayout()
        self.ui.scrollAreaWidgetContents.setLayout(self.welch_psd_layout)

        # Create and embed the Parameters plot widget
        self.parameters_plot_widget = spQt.ParametersPlotWidget()
        layout5 = QVBoxLayout()
        layout5.addWidget(self.parameters_plot_widget)
        self.ui.mplParameters.setLayout(layout5)

        # Connect UI signals to their handlers
        self.ui.treeWidget.itemSelectionChanged.connect(self.on_file_selection)
        self.ui.Views.currentChanged.connect(self.on_tab_changed)
        self.dataset = None  # Initialize dataset placeholder

    def OpenWorkSpace(self):
        """
        Open a JSON workspace file, holding the directories.
        """
        file_path, _ = QFileDialog.getOpenFileName(
            self, "Select a file", "", "workspace Files (*.json);;Text Files (*.txt)"
        )
        self.workspace = spQt.LoadWorkspace(file_path)
        spQt.PopulateTree(self.ui.treeWidget, self.workspace)

    def SaveWorkSpace(self):
        """
        Save a JSON workspace file, holding the directories.
        """
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Select a file", "", "workspace Files (*.json);;Text Files (*.txt)"
        )
        if file_path:
            try:
                # Save the workspace to the selected file
                with open(file_path, "w") as file:
                    json.dump(self.workspace, file, indent=4)
            except Exception as e:
                pass

    def EditWorkSpace(self):
        """
        Edit a JSON workspace file, holding the directories.
        """
        dialog = spQt.DirectorySelectorDialog(self.workspace)
        if dialog.exec_() == QInputDialog.Accepted:
            # Update the workspace with the new directories
            self.workspace = dialog.get_directories()
            spQt.PopulateTree(self.ui.treeWidget, self.workspace)

    def show_context_menu(self, position):
        """
        Show a context menu at the specified position.

        Args:
            position (QPoint): The position where the context menu is requested.
        """
        # Get the item that was clicked
        item = self.ui.treeWidget.itemAt(position)
        if not item:
            return

        # Only allow context menu for raw files: the ones with ecg data
        if (
            not item.text(0).lower().endswith(".xdf")
            and not item.text(0).lower().endswith(".txt")
            and not item.text(0).lower().endswith(".evt")
        ):
            return

        # Create a context menu
        context_menu = QMenu(self)

        # Create actions for the context menu
        reload_action = QAction("Reload Raw", self)
        invert_action = QAction("Invert ECG Polarity", self)
        retrigger_action = QAction("Retrigger ECG", self)
        classify_action = QAction("(Re-)Classify RTops", self)

        # Connect the actions to their respective functions
        reload_action.triggered.connect(lambda: self.reload(item))
        invert_action.triggered.connect(self.invert)
        retrigger_action.triggered.connect(self.retrigger)
        classify_action.triggered.connect(self.reClassify)

        # Add the actions to the context menu
        context_menu.addAction(reload_action)
        context_menu.addAction(invert_action)
        context_menu.addAction(retrigger_action)
        context_menu.addAction(classify_action)
        # Show the context menu at the requested position
        context_menu.exec_(self.ui.treeWidget.viewport().mapToGlobal(position))

    def reClassify(self):
        """
        Reclassify the R-peaks in the ECG signal and update the preprocessing plot.
        """
        if self.dataset is None:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        ibiClassify(self.dataset.rtops)
        self.dataset.save(self.savename)  # Save the reclassified dataset
        QApplication.restoreOverrideCursor()
        self.show_preprocessing_plot(self.dataset)

    def retrigger(self):
        """
        Retrigger the ECG signal by recalculating the R-peaks and updating the preprocessing plot.
        """
        if self.dataset is None:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        self.dataset.rtops = None  # Clear existing RTops to force retriggering
        for key, epoch in self.dataset.epochs.items():
            if epoch.active:
                logger.info(f"Retriggering epoch: {key}")
                calcPeaks(
                    self.dataset["ecg"][key],
                    min_peak_distance_ms=300.0,
                    classify=True,
                )

        QApplication.restoreOverrideCursor()
        self.dataset.save(self.savename)  # Save the retriggered dataset
        self.show_preprocessing_plot(self.dataset)

    def reload(self, item):
        """
        Reload the selected file and update the preprocessing plot.

        Args:
            item: The selected item in the tree view.
        """
        self.dataset = spQt.PreProcessFile(
            self.workspace, item.text(0), reset=True, border=False
        )
        self.dataset.save(self.savename)  # Save the reloaded dataset
        self.show_preprocessing_plot(self.dataset)

    def invert(self):
        """
        Invert the ECG polarity and update the preprocessing plot.
        """
        if self.dataset is None:
            return

        self.dataset["ecg"].timeseries.flip()
        cs.Actions.calcPeaks(self.dataset)
        self.dataset.save(self.savename)  # Save the inverted dataset
        self.show_preprocessing_plot(self.dataset)

    def on_tab_changed(self, index):
        """
        Handler triggered when the user switches tabs in the UI.

        Parameters
        ----------
        index : int
            The index of the newly selected tab.
        """
        QApplication.setOverrideCursor(Qt.WaitCursor)

        if self.dataset is not None:
            self.dataset.save(self.savename)  # Save the current dataset

        if index == 1 and self.dataset is not None:
            self.show_hr_plot(self.dataset)

        if index == 2 and self.dataset is not None:
            self.show_poincare_plot(self.dataset)

        if index == 3 and self.dataset is not None:
            # self.show_poincare_plot(self.dataset)
            self.show_epoch_plot(self.dataset)

        if index == 4 and self.dataset is not None:
            # self.show_poincare_plot(self.dataset)
            self.show_welch_psd_plot(self.dataset)

        if index == 5 and self.dataset is not None:
            # self.show_poincare_plot(self.dataset)
            self.show_parameters_plot(self.dataset)

        QApplication.restoreOverrideCursor()

    def on_file_selection(self):
        """
        Handler triggered when the user selects a file from the workspace tree.
        It loads and preprocesses the selected file, then updates all
        the plots accordingly.
        """

        selected_items = self.ui.treeWidget.selectedItems()
        if not selected_items:
            return

        item = selected_items[0]
        meta = item.data(0, Qt.UserRole)

        # Ignore category headers
        if meta is None:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)

        # --------------------------------------------------
        # CASE 1: Dataset root node
        # --------------------------------------------------
        if meta.get("type") == "dataset":
            filename = meta["filename"]

            self.savename = Path(self.workspace["CacheDirectory"]) / (
                Path(filename).stem + ".pkl"
            )

            # Load dataset (cached or fresh)
            if Path(self.savename).exists():
                with open(self.savename, "rb") as f:
                    dataset = pickle.load(f)
            else:
                dataset = spQt.PreProcessFile(self.workspace, filename)
                if dataset.active_band is None:
                    dataset.active_band = next(iter(dataset.band_map))
                dataset.save(self.savename)

            # Detect Polar band IDs from timeseries names
            band_ids = sorted(
                {
                    name.split("[")[-1][:-1]
                    for name in dataset.timeseries
                    if "[" in name and "]" in name
                }
            )

            # --------------------------------------------------
            # Multiple bands → expand tree only (no plotting)
            # --------------------------------------------------
            if len(band_ids) > 1:
                if not meta.get("bands_expanded", False):
                    item.takeChildren()

                    for band in band_ids:
                        child = QTreeWidgetItem(item, [f"Band {band}"])
                        child.setData(
                            0,
                            Qt.UserRole,
                            {
                                "type": "band",
                                "band_id": band,
                                "filename": filename,
                            },
                        )

                    meta["bands_expanded"] = True
                    item.setData(0, Qt.UserRole, meta)
                    item.setExpanded(True)

                # Do NOT plot yet
                QApplication.restoreOverrideCursor()
                return

            # --------------------------------------------------
            # Single band → behave exactly as before
            # --------------------------------------------------
            self.dataset = dataset
            if dataset.has_ecg:
                self.show_preprocessing_plot(self.dataset)
                self.ui.Views.setTabVisible(0, True)
            else:
                self.ui.Views.setTabVisible(0, False)

            self.show_hr_plot(self.dataset)
            self.show_poincare_plot(self.dataset)
            self.show_epoch_plot(self.dataset)
            self.show_welch_psd_plot(self.dataset)
            self.show_parameters_plot(self.dataset)
            QApplication.restoreOverrideCursor()
            return

        # --------------------------------------------------
        # CASE 2: Band node
        # --------------------------------------------------
        if meta.get("type") == "band":
            filename = meta["filename"]
            band_id = meta["band_id"]

            self.savename = Path(self.workspace["CacheDirectory"]) / (
                Path(filename).stem + ".pkl"
            )

            if self.savename.exists():
                with open(self.savename, "rb") as f:
                    dataset = pickle.load(f)
                    dataset.active_band = band_id
            else:
                dataset.active_band = band_id
                dataset = spQt.PreProcessFile(self.workspace, filename)
                dataset.save(self.savename)

            self.dataset = dataset
            # Plot as usual
            self.show_preprocessing_plot(self.dataset)
            self.show_hr_plot(self.dataset)
            self.show_poincare_plot(self.dataset)
            self.show_epoch_plot(self.dataset)
            self.show_welch_psd_plot(self.dataset)
            self.show_parameters_plot(self.dataset)

        QApplication.restoreOverrideCursor()

    def show_preprocessing_plot(self, data):
        """
        Display the ECG preprocessing results in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing preprocessed ECG signals.
        """
        if hasattr(data, "has_ecg") and data.has_ecg:
            self.ui.Views.setTabVisible(0, True)
            self.ui.Views.setCurrentIndex(0)
            self.prep_plot_widget.prepPlot(data)
        else:
            self.ui.Views.setTabVisible(0, False)
            # self.hr_plot_widget.hrPlot(data)
            self.ui.Views.setCurrentIndex(1)

    def show_hr_plot(self, data):
        """
        Display the HeartRate series plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.hr_plot_widget.hrPlot(data)

    def show_epoch_plot(self, data):
        """
        Display the plot of the epochs in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing epoch information.
        """
        if data is not None:
            self.epoch_plot_widget.plotEpochs(data)

    def show_poincare_plot(self, data):
        """
        Display the Poincaré plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if data is not None:
            self.poincare_plot_widget.poincarePlot(data)

    def show_welch_psd_plot(self, dataset):
        # ---------------------------------------------
        # Clear previous widgets
        # ---------------------------------------------
        while self.welch_psd_layout.count():
            item = self.welch_psd_layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.setParent(None)
                widget.deleteLater()

        # ---------------------------------------------
        # Collect active epoch views
        # ---------------------------------------------
        pairs = []
        for label, epoch in dataset.epochs.items():
            if not epoch.active:
                continue
            try:
                pairs.append((label, dataset.hrv[label]))
            except Exception:
                continue

        if not pairs:
            return

        labels, views = zip(*pairs)

        # ---------------------------------------------
        # Global axis normalization
        # ---------------------------------------------
        ymin, ymax = spQt.WelchPSDPlotWidget.probe_limits(
            views,
            fs=4,
            interpolate=True,
        )

        # ---------------------------------------------
        # Plot widgets
        # ---------------------------------------------
        for label, view in pairs:
            widget = spQt.WelchPSDPlotWidget()
            widget.plot(view, fs=4, interpolate=True)

            widget.ax.set_ylim(ymin, ymax)
            widget.ax.set_title(f"PSD – {label}")

            self.welch_psd_layout.addWidget(widget)

        self.ui.scrollArea.setWidgetResizable(True)
        self.ui.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)

    def show_parameters_plot(self, data):
        """
        Display the parameters plot of the ECG signal in the appropriate widget.

        Parameters
        ----------
        data : object
            The dataset object containing RR intervals or relevant features.
        """
        if data is not None:
            self.parameters_plot_widget.display_parameters(data, self.workspace)

    def add_epoch(self):
        """
        Prompt the user for an epoch label and add it to the dataset with the start and end times
        set to the full range of the dataset.
        """
        if self.dataset is None:
            return

        # Prompt the user for an epoch label
        epoch_label, ok = QInputDialog.getText(self, "Add Epoch", "Epoch Label:")
        if not ok or not epoch_label:
            return

        # Get the full range of the dataset
        if "ecg" in self.dataset.timeseries:
            start_time = self.dataset["ecg"].timeseries.times[0]
            end_time = self.dataset["ecg"].timeseries.times[-1]

        elif hasattr(self.dataset, "hrv") and self.dataset.hrv is not None:
            start_time = self.dataset.hrv.times[0]
            end_time = self.dataset.hrv.times[-1]

        # Add the new epoch to the dataset
        self.dataset.epochs[epoch_label] = Epoch(
            active=True,
            start=start_time,
            end=end_time,
        )

        # Replot the figure to include the new epoch
        # self.poincare_plot_widget.poincarePlot(self.dataset)
        self.epoch_plot_widget.plotEpochs(self.dataset)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    # Set global default font
    default_font = QFont("Segoe UI", 12)
    default_font.setBold(False)
    app.setStyle("WindowsVista")
    app.setFont(default_font)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
