name: spectHR
channels:
  - conda-forge
  - anaconda
dependencies:
  - mamba
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - mplcursors
  - numpy
  - pandas
  - python>=3.7
  - pyxdf
  - scipy
  - pip
  - pip:
    - easywebdav
