name: spectHRDev
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - mplcursors
  - numpy
  - pandas
  - pip
  - python
  - scipy
  - setuptools_scm
  - voila
  - voila-gridstack
  - seaborn
  - wheel
  - nb_conda_kernels
  - pip:
    - spectHR>=0.1.10

