name: spectHRDev
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyterlab
  - matplotlib
  - mplcursors
  - numpy
  - pandas
  - pip
  - python
  - scipy
  - wheel
  - spectHR

