name: spectHR
channels:
  - conda-forge
  - anaconda
dependencies:
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - mplcursors
  - numpy
  - pandas
  - pip
  - pillow
  - python
  - scipy
  - voila
  - voila-gridstack
  - seaborn
  - wheel
