name: spectHR
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter>=1.0
  - jupyterlab>=4.0.0
  - matplotlib>=3.1.2
  - mplcursors
  - numpy>=1.17
  - pandas
  - pip
  - pillow>=6.2
  - python>=3.10
  - scipy>=1.3.2
  - voila
  - voila-gridstack
  - seaborn
  - wheel
  - nb_conda_kernels
  - pip:
    - spectHR >=0.1.10
    - jupytercontrib>=0.0.7
